name: vault-agent
replicas: 1

image: ${artifact.metadata.image}

createNamespace: true
namespace: ${infra.kubernetes.namespace}

pvcsinkfilename: vault-agent-sink-pvc

env:
  config:
    vault_agent_config: |
      pid_file = "/etc/vault/pidfile"

      vault {
        address = "http://15.228.43.18:8200"
        tls_skip_verify = true
        retry {
          num_retries = 5
        }
      }

      auto_auth {
        method "approle" {
          config = {
            role_id_file_path = "/etc/vault/credentials/roleid"
            secret_id_file_path = "/etc/vault/credentials/secretid"
            remove_secret_id_file_after_reading = false
          }
        }

        sink "file" {
          config = {
            path = "/etc/vault/sink_shared/sink"
          }
        }
      }

      cache {
        use_auto_auth_token = true
      }


      listener "tcp" {
        address = "127.0.0.1:8100"
        tls_disable = true
      }
  secrets:
    roleid: ${secrets.getValue(${workflow.variables.roleid_secretname})}
    secretid: ${secrets.getValue(${workflow.variables.secretid_secretname})}
